# Generated by Django 4.0.3 on 2022-03-14 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketchbookapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
    ]
