# Generated by Django 4.0.3 on 2022-03-15 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sketchbookapi', '0002_rename_author_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='created_on',
        ),
    ]
