# Generated by Django 4.0.3 on 2022-04-15 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchbookapi', '0002_checklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='publication_date',
            field=models.DateField(auto_now=True),
        ),
    ]
