# Generated by Django 4.0.3 on 2022-03-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketchbookapi', '0003_remove_comment_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_url',
            field=models.ImageField(null=True, upload_to='actionimages'),
        ),
    ]
